server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}/v1
spring:
  application:
    name: mssivimss-cat-servicios
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      

      
  main:
    allow-circular-references: true
    
  
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

logos:
  msit_logo_imss: /sintrans_data/LOGOS/logoImss.png
  msit_logo_sistema: /sintrans_data/LOGOS/logoSistema.png

endpoints:
    ms-mod-catalogos: http://localhost:8090/mssivimss-mod-catalogos/v1/generico
    renapo: http://localhost:8088/mssivimss-reportes-jasp/v1/generales/generar-reporte
    rutas:
      dominio-consulta: ${endpoints.ms-mod-catalogos}/consulta
      dominio-consulta-paginado: ${endpoints.ms-mod-catalogos}/paginado
      dominio-crear: ${endpoints.ms-mod-catalogos}/crear
      dominio-crear-multiple: ${endpoints.ms-mod-catalogos}/crearMultiple
      dominio-actualizar: ${endpoints.ms-mod-catalogos}/actualizar
      dominio-insertar-multiple: ${endpoints.ms-mod-catalogos}/insertarMultiple
jwt:
  secretkey-flujo: funcionamuybien
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: 360
  
formato_fecha: '%d/%m/%Y'
ruta-log: 'C:/logs/'